export const queryKeys = Object.freeze({
  jobs: (filters = {}) => ['jobs', filters],
  job: (jobId) => ['job', jobId],
  companies: (filters = {}) => ['companies', filters],
  company: (companyId) => ['company', companyId],
  companyJobs: (companyId, filters = {}) => ['company-jobs', companyId, filters],
  jobMatch: (jobId) => ['job-match', jobId],
  applicantApplications: () => ['applicant', 'applications'],
  applicantApplication: (applicationId) => ['applicant', 'applications', applicationId],
  savedJobs: () => ['applicant', 'saved-jobs'],
  applicantProfile: () => ['applicant', 'profile'],
  applicantResumes: () => ['applicant', 'resumes'],
  recruiterJobs: (recruiterId = 'demo-recruiter') => ['recruiter-jobs', recruiterId],
  jobApplicants: (jobId) => ['job-applicants', jobId],
  notifications: (role) => ['notifications', role],
});
