export const queryKeys = Object.freeze({
  jobs: (filters = {}) => ['jobs', filters],
  job: (jobId) => ['job', jobId],
  companies: (filters = {}) => ['companies', filters],
  company: (companyId) => ['company', companyId],
  companyJobs: (companyId, filters = {}) => ['company-jobs', companyId, filters],
  jobMatch: (jobId) => ['job-match', jobId],
  applicantApplications: () => ['applicant', 'applications'],
  applicantApplication: (applicationId) => ['applicant', 'applications', applicationId],
  savedJobs: () => ['applicant', 'saved-jobs'],
  applicantProfile: () => ['applicant', 'profile'],
  applicantResumes: () => ['applicant', 'resumes'],
  applicantDashboard: () => ['applicant', 'dashboard'],
  recruiterDashboard: () => ['recruiter', 'dashboard'],
  settings: () => ['settings'],
  recruiterJobs: (recruiterId = 'demo-recruiter') => ['recruiter-jobs', recruiterId],
  recruiterJob: (jobId) => ['recruiter-jobs', jobId],
  recruiterCompany: () => ['recruiter', 'company'],
  jobApplicants: (jobId, filters = {}) => ['job-applicants', jobId, filters],
  recruiterApplication: (applicationId) => ['recruiter', 'applications', applicationId],
  recruiterNotes: (applicationId) => ['recruiter', 'applications', applicationId, 'notes'],
  notifications: (role) => ['notifications', role],
});
