export const demoAccounts = Object.freeze({
  applicant: {
    id: 'demo-applicant',
    email: 'applicant@careerbridge.demo',
    name: 'Ananya Rao',
    role: 'APPLICANT',
  },
  recruiter: {
    id: 'demo-recruiter',
    email: 'recruiter@careerbridge.demo',
    name: 'Rohan Mehta',
    role: 'RECRUITER',
  },
  admin: {
    id: 'demo-admin',
    email: 'admin@careerbridge.demo',
    name: 'CareerBridge Admin',
    role: 'ADMIN',
  },
});

export const companies = [
  {
    id: 'northstar-labs',
    name: 'Northstar Labs',
    slug: 'northstar-labs',
    description:
      'Northstar Labs builds reliable developer infrastructure for fast-moving product teams.',
    website: 'https://northstarlabs.example',
    industry: 'Developer tools',
    companyType: 'Product',
    size: '201–500 employees',
    foundedYear: 2018,
    headquarters: 'Bengaluru, Karnataka',
    locations: ['Bengaluru, Karnataka', 'Remote, India'],
    benefits: [
      'Learning budget',
      'Hybrid flexibility',
      'Health insurance',
      'Mentor programme',
    ],
    brandInitials: 'NL',
    brandColor: '#2658d8',
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'greenroute-mobility',
    name: 'GreenRoute Mobility',
    slug: 'greenroute-mobility',
    description:
      'GreenRoute makes urban transport cleaner through connected electric mobility systems.',
    website: 'https://greenroute.example',
    industry: 'Clean mobility',
    companyType: 'Startup',
    size: '501–1,000 employees',
    foundedYear: 2019,
    headquarters: 'Pune, Maharashtra',
    locations: ['Pune, Maharashtra'],
    benefits: [
      'Electric commute support',
      'Flexible leave',
      'Health insurance',
      'Field learning days',
    ],
    brandInitials: 'GM',
    brandColor: '#168a67',
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'meridian-fintech',
    name: 'Meridian Fintech',
    slug: 'meridian-fintech',
    description:
      'Meridian creates accessible financial tools for growing businesses across India.',
    website: 'https://meridianfintech.example',
    industry: 'Financial technology',
    companyType: 'Product',
    size: '201–500 employees',
    foundedYear: 2016,
    headquarters: 'Mumbai, Maharashtra',
    locations: ['Mumbai, Maharashtra', 'Bengaluru, Karnataka'],
    benefits: [
      'Learning allowance',
      'Hybrid flexibility',
      'Wellness cover',
      'Volunteer leave',
    ],
    brandInitials: 'MF',
    brandColor: '#0a829b',
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'paperplane-studio',
    name: 'Paperplane Studio',
    slug: 'paperplane-studio',
    description:
      'Paperplane is a research-led design studio shaping thoughtful digital products.',
    website: 'https://paperplane.example',
    industry: 'Product design',
    companyType: 'Consulting',
    size: '51–200 employees',
    foundedYear: 2020,
    headquarters: 'Remote, India',
    locations: ['Remote, India'],
    benefits: [
      'Remote-first work',
      'Design conference budget',
      'Studio retreats',
      'Flexible hours',
    ],
    brandInitials: 'PS',
    brandColor: '#b97813',
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'clinivo-health',
    name: 'Clinivo Health',
    slug: 'clinivo-health',
    description:
      'Clinivo helps care teams coordinate patient journeys with secure digital tools.',
    website: 'https://clinivo.example',
    industry: 'Health technology',
    companyType: 'Product',
    size: '201–500 employees',
    foundedYear: 2017,
    headquarters: 'Hyderabad, Telangana',
    locations: ['Hyderabad, Telangana'],
    benefits: [
      'Family health cover',
      'Hybrid flexibility',
      'Learning budget',
      'Wellness days',
    ],
    brandInitials: 'CH',
    brandColor: '#c43d4f',
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'orbit-learning',
    name: 'Orbit Learning',
    slug: 'orbit-learning',
    description:
      'Orbit builds practical learning experiences for students entering the modern workplace.',
    website: 'https://orbitlearning.example',
    industry: 'Education technology',
    companyType: 'Startup',
    size: '51–200 employees',
    foundedYear: 2021,
    headquarters: 'Chennai, Tamil Nadu',
    locations: ['Chennai, Tamil Nadu', 'Remote, India'],
    benefits: [
      'Remote-friendly work',
      'Course allowance',
      'Flexible leave',
      'Quarterly offsites',
    ],
    brandInitials: 'OL',
    brandColor: '#6c5ce7',
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'harbor-commerce',
    name: 'Harbor Commerce',
    slug: 'harbor-commerce',
    description:
      'Harbor helps independent retailers manage catalogues, fulfilment, and customer insight.',
    website: 'https://harborcommerce.example',
    industry: 'Retail technology',
    companyType: 'MNC',
    size: '501–1,000 employees',
    foundedYear: 2014,
    headquarters: 'Gurugram, Haryana',
    locations: ['Gurugram, Haryana'],
    benefits: [
      'Health insurance',
      'Learning allowance',
      'Hybrid flexibility',
      'Employee assistance',
    ],
    brandInitials: 'HC',
    brandColor: '#2a6fd6',
    verificationStatus: 'VERIFIED',
  },
];

const publishedAt = new Date('2026-09-01T09:00:00.000Z');
const deadline = new Date('2026-10-15T18:29:59.000Z');

export const jobs = [
  [
    'frontend-engineer-northstar',
    'Graduate Frontend Engineer',
    'northstar-labs',
    'Engineering',
    'Software development',
    'Bengaluru, Karnataka',
    'HYBRID',
    'FULL_TIME',
    0,
    1,
    600000,
    800000,
    ['React', 'JavaScript', 'CSS', 'Git'],
    ['Accessibility', 'Playwright'],
    'Build accessible product interfaces alongside a supportive developer-platform team.',
  ],
  [
    'qa-engineer-northstar',
    'Quality Engineer',
    'northstar-labs',
    'Engineering',
    'Quality assurance',
    'Bengaluru, Karnataka',
    'HYBRID',
    'FULL_TIME',
    1,
    2,
    600000,
    900000,
    ['Playwright', 'JavaScript', 'API testing'],
    ['CI/CD', 'Accessibility'],
    'Own thoughtful test coverage across user journeys and platform APIs.',
  ],
  [
    'data-analyst-meridian',
    'Junior Data Analyst',
    'meridian-fintech',
    'Data',
    'Data and analytics',
    'Mumbai, Maharashtra',
    'HYBRID',
    'FULL_TIME',
    0,
    1,
    550000,
    700000,
    ['SQL', 'Excel', 'Power BI', 'Python'],
    ['Statistics'],
    'Turn product and transaction data into clear insights for cross-functional teams.',
  ],
  [
    'risk-analyst-meridian',
    'Risk Operations Analyst',
    'meridian-fintech',
    'Risk',
    'Operations',
    'Mumbai, Maharashtra',
    'HYBRID',
    'FULL_TIME',
    1,
    2,
    600000,
    800000,
    ['Risk analysis', 'SQL', 'Excel'],
    ['Python'],
    'Review portfolio signals and improve fair, consistent operational decisions.',
  ],
  [
    'business-analyst-greenroute',
    'Associate Business Analyst',
    'greenroute-mobility',
    'Operations',
    'Business analysis',
    'Pune, Maharashtra',
    'ON_SITE',
    'FULL_TIME',
    0,
    1,
    500000,
    700000,
    ['Analysis', 'Excel', 'Communication', 'SQL'],
    ['Fleet analytics'],
    'Connect operations data with decisions that improve electric fleet performance.',
  ],
  [
    'operations-intern-greenroute',
    'Operations Intern',
    'greenroute-mobility',
    'Operations',
    'Operations',
    'Pune, Maharashtra',
    'ON_SITE',
    'INTERNSHIP',
    0,
    0,
    240000,
    240000,
    ['Operations', 'Excel', 'Problem solving'],
    ['Communication'],
    'Support fleet operations and learn how sustainable mobility scales city by city.',
  ],
  [
    'product-design-intern-paperplane',
    'Product Design Intern',
    'paperplane-studio',
    'Design',
    'Product design',
    'Remote, India',
    'REMOTE',
    'INTERNSHIP',
    0,
    0,
    300000,
    300000,
    ['Figma', 'User research', 'Prototyping'],
    ['Usability testing'],
    'Learn through real discovery and interface projects with experienced product designers.',
  ],
  [
    'ux-researcher-paperplane',
    'Junior UX Researcher',
    'paperplane-studio',
    'Research',
    'Product design',
    'Remote, India',
    'REMOTE',
    'FULL_TIME',
    0,
    1,
    500000,
    700000,
    ['Interviews', 'Synthesis', 'Usability testing'],
    ['Figma'],
    'Plan and synthesise research that helps teams make grounded product decisions.',
  ],
  [
    'backend-engineer-clinivo',
    'Backend Engineer I',
    'clinivo-health',
    'Engineering',
    'Software development',
    'Hyderabad, Telangana',
    'HYBRID',
    'FULL_TIME',
    1,
    2,
    700000,
    1000000,
    ['Node.js', 'PostgreSQL', 'REST APIs'],
    ['Docker'],
    'Create dependable services for secure patient and care-team workflows.',
  ],
  [
    'customer-success-clinivo',
    'Customer Success Associate',
    'clinivo-health',
    'Customer success',
    'Customer success',
    'Hyderabad, Telangana',
    'ON_SITE',
    'FULL_TIME',
    0,
    1,
    480000,
    620000,
    ['Communication', 'Healthcare', 'CRM'],
    ['Analytics'],
    'Guide care teams through onboarding and help them get lasting value from Clinivo.',
  ],
  [
    'growth-associate-orbit',
    'Graduate Growth Associate',
    'orbit-learning',
    'Growth',
    'Marketing',
    'Chennai, Tamil Nadu',
    'ON_SITE',
    'FULL_TIME',
    0,
    0,
    450000,
    600000,
    ['Content', 'Analytics', 'Campaigns'],
    ['Excel'],
    'Help more students discover practical learning programmes through measurable campaigns.',
  ],
  [
    'content-intern-orbit',
    'Learning Content Intern',
    'orbit-learning',
    'Content',
    'Education',
    'Chennai, Tamil Nadu',
    'HYBRID',
    'INTERNSHIP',
    0,
    0,
    216000,
    216000,
    ['Writing', 'Research', 'Editing'],
    ['SEO'],
    'Create clear, useful learning material with subject experts and student feedback.',
  ],
  [
    'catalog-analyst-harbor',
    'E-commerce Catalog Analyst',
    'harbor-commerce',
    'Catalog',
    'Data and analytics',
    'Gurugram, Haryana',
    'HYBRID',
    'FULL_TIME',
    0,
    1,
    480000,
    650000,
    ['Excel', 'Data quality', 'E-commerce'],
    ['SQL'],
    'Improve the structure and quality of retailer catalogues at meaningful scale.',
  ],
  [
    'support-engineer-harbor',
    'Technical Support Engineer',
    'harbor-commerce',
    'Support',
    'Customer success',
    'Gurugram, Haryana',
    'ON_SITE',
    'FULL_TIME',
    1,
    2,
    550000,
    750000,
    ['Troubleshooting', 'SQL', 'APIs'],
    ['JavaScript'],
    'Solve product issues with empathy and turn recurring patterns into platform improvements.',
  ],
].map(
  (
    [
      id,
      title,
      companyId,
      department,
      category,
      location,
      workMode,
      employmentType,
      experienceMin,
      experienceMax,
      salaryMin,
      salaryMax,
      requiredSkills,
      preferredSkills,
      summary,
    ],
    index,
  ) => ({
    id,
    slug: id,
    title,
    companyId,
    department,
    category,
    location,
    workMode,
    employmentType,
    experienceMin,
    experienceMax,
    salaryMin,
    salaryMax,
    requiredSkills,
    preferredSkills,
    summary,
    description: `${summary} You will collaborate with a multidisciplinary team, learn through feedback, and deliver measurable improvements for customers.`,
    responsibilities: [
      'Deliver scoped work with clear quality standards',
      'Collaborate with teammates and communicate progress',
      'Use feedback and evidence to improve outcomes',
    ],
    qualification:
      'Recent graduates and early-career candidates with relevant project, coursework, internship, or work evidence are encouraged to apply.',
    openings: index % 4 === 0 ? 2 : 1,
    featured: index < 6,
    status: 'PUBLISHED',
    moderationStatus: 'CLEARED',
    publishedAt,
    deadline,
  }),
);

export const candidateProfiles = [
  {
    id: 'candidate-kavya',
    email: 'kavya.nair@careerbridge.demo',
    name: 'Kavya Nair',
    headline: 'Frontend developer · 1 year experience',
    location: 'Bengaluru, Karnataka',
    skills: ['React', 'JavaScript', 'CSS', 'Git', 'Accessibility'],
    jobId: 'frontend-engineer-northstar',
    status: 'SHORTLISTED',
  },
  {
    id: 'candidate-arjun',
    email: 'arjun.menon@careerbridge.demo',
    name: 'Arjun Menon',
    headline: 'Computer science graduate',
    location: 'Kochi, Kerala',
    skills: ['React', 'JavaScript', 'Git', 'REST APIs'],
    jobId: 'frontend-engineer-northstar',
    status: 'UNDER_REVIEW',
  },
  {
    id: 'candidate-meera',
    email: 'meera.joshi@careerbridge.demo',
    name: 'Meera Joshi',
    headline: 'UI engineer · internship experience',
    location: 'Pune, Maharashtra',
    skills: ['React', 'Figma', 'Accessibility', 'Prototyping'],
    jobId: 'frontend-engineer-northstar',
    status: 'INTERVIEW',
  },
  {
    id: 'candidate-neel',
    email: 'neel.iyer@careerbridge.demo',
    name: 'Neel Iyer',
    headline: 'Data analyst · finance projects',
    location: 'Mumbai, Maharashtra',
    skills: ['SQL', 'Python', 'Excel', 'Power BI'],
    jobId: 'data-analyst-meridian',
    status: 'INTERVIEW',
  },
  {
    id: 'candidate-vikram',
    email: 'vikram.das@careerbridge.demo',
    name: 'Vikram Das',
    headline: 'Backend developer · 2 years',
    location: 'Hyderabad, Telangana',
    skills: ['Node.js', 'PostgreSQL', 'REST APIs', 'Docker'],
    jobId: 'backend-engineer-clinivo',
    status: 'UNDER_REVIEW',
  },
];
